"use client";

import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  es: {
    // Common texts
    common: {
      cancel: "Cancelar",
      accept: "Aceptar",
      edit: "Editar",
      delete: "Eliminar",
      save: "Guardar",
      help: "Ayuda",
      create: "Crear",
      saving: "Guardando...",
      loading: "Cargando...",
      newProject: "Nuevo Proyecto",
      requests: "Peticiones",
      pending: "Pendiente",
      active: "Activo",
      completed: "Completado",
      admin: "Administrador",
      control: "Control",
      projectRequests: "Peticiones de Proyectos",
      noPendingRequests: "No hay peticiones pendientes",
      requestProject: "Solicitar Proyecto",
      search: "Buscar proyectos, ubicaciones...",
    },

    // Profile section
    profile: {
      editProfile: "Editar Perfil",
      fullName: "Nombre completo",
      fullNamePlaceholder: "Tu nombre completo",
      email: "Correo electrónico",
      emailPlaceholder: "ejemplo@email.com",
      role: "Rol",
      organization: "Información de organización",
      orgName: "Nombre de la organización",
      orgNamePlaceholder: "Nombre de la organización",
      website: "Sitio web",
      websitePlaceholder: "https://...",
      changePassword: "Cambiar contraseña (opcional)",
      currentPassword: "Contraseña actual",
      currentPasswordPlaceholder: "Requerida para cambiar contraseña",
      newPassword: "Nueva contraseña",
      newPasswordPlaceholder: "Mínimo 6 caracteres",
      nameRequired: "✕ Nombre requerido",
      invalidEmail: "✕ Email inválido",
      saveChanges: "Guardar cambios",
      cancel: "Cancelar",
      validateFields: "Por favor corrige los campos marcados",
      enterCurrentPassword: "Ingresa tu contraseña actual para cambiarla",
      updateSuccess: "¡Perfil actualizado correctamente!",
      updatePasswordSuccess: "¡Perfil y contraseña actualizados correctamente!",
      updateError: "Error al actualizar el perfil",
      minChars: "✕ Mínimo 6 caracteres",
    },

    // Admin section
    admin: {
      titulo: "Administration Panel",
      subtitulo: "Manage reforestation projects in Manabí",
      projectRequests: "Project Requests",
      noPendingRequests: "No pending requests",
      viewRequests: "View Requests",
      requests: "Requests",
      editButton: "Edit",
      deleteButton: "Delete",
      confirmDelete: "Are you sure you want to delete this project?",
      editProject: "Edit Project",
      newProject: "New Project",
      requestProject: "Request Project",
      status: "Status",
      active: "Active",
      statsTitle: "Project Overview",
      totalProjects: "Total Projects",
      totalVolunteers: "Total Volunteers",
      noProjects: "No Projects Yet",
      noProjectsDesc: "Create your first project to get started",
      location: "Location",
      trees: "Trees",
      volunteers: "Volunteers",
      species: "Species",
      date: "Date",
      description: "Description",
      organizationInfo: "Organization Information",
      coordinates: "Coordinates",
      upcomingStatus: "Upcoming",
      inProgressStatus: "In Progress",
      completedStatus: "Completed",
      saveChanges: "Save Changes",
      projectName: "Project Name",
      projectNamePlaceholder: "Enter project name",
      nuevoProyecto: "Nuevo Proyecto",
      noHayProyectos: "No Hay Proyectos Aún",
      noHayProyectosDesc: "Agrega tu primer proyecto para empezar",
      addProject: "Agregar proyecto",
      editProject: "Editar proyecto",
      deleteProject: "Eliminar proyecto",
      projectName: "Nombre del proyecto",
      location: "Ubicación",
      trees: "Árboles",
      volunteers: "Voluntarios",
      species: "Especies",
      date: "Fecha",
      status: "Estado",
      description: "Descripción",
      upcoming: "Próximo",
      inProgress: "En progreso",
      completed: "Completado",
      save: "Guardar",
      cancel: "Cancelar",
      confirmDelete: "¿Estás seguro de que quieres eliminar este proyecto?",
      noOrganizersAvailable: "No hay organizadores disponibles. Agrega usuarios con rol organizador.",
      deleteSuccess: "Proyecto eliminado correctamente",
      saveSuccess: "Proyecto guardado correctamente",
      selectLocation: "Seleccionar ubicación",
      otherLocation: "Otra ubicación",
      writeLocation: "Ingresa el nombre de la ubicación",
      coordinates: "Coordenadas",
      coordinatesHelp: "Haz clic en el mapa para seleccionar coordenadas o ingresa manualmente",
      customCoordinates: "Para coordenadas personalizadas, puedes usar",
      requestProject: "Solicitar Proyecto",
      projectDescription: "Descripción del proyecto",
      projectStatus: "Estado del proyecto",
      activeProjects: "Proyectos activos",
      upcomingStatus: "Próximo",
      inProgressStatus: "En progreso",
      completedStatus: "Completado",
      organizers: "Organizadores",
      organizersHelp: "Asignar organizadores para gestionar este proyecto",
      saveProject: "Guardar Proyecto",
      editProject: "Editar Proyecto",
      deleteProject: "Eliminar Proyecto",
      confirmDelete: "¿Estás seguro de que quieres eliminar este proyecto?",
      deleteSuccess: "Proyecto eliminado correctamente",
      saveSuccess: "Proyecto guardado correctamente",
      saveError: "Error al guardar el proyecto",
      peticiones: "Peticiones",
    },

    // Sidebar
    sidebar: {
      inicio: "Inicio",
      proyectos: "Proyectos",
      estadisticas: "Estadísticas",
      acceso: "Acceso",
      registro: "Registro",
      tuImpacto: "Tu Impacto",
      arboles: "árboles",
      faltan: "Faltan",
      arbolesParaMeta: "árboles para tu meta semanal",
      modoOscuro: "Modo oscuro",
      modoClaro: "Modo claro", 
      espanol: "Español",
      ingles: "English",
      acceder: "Acceder",
      admin: "Administración",
      organizer: "Organizador",
      perfil: "Perfil",
      control: "Control",
      voluntarios: "Voluntarios",
    },

    // Accessibility menu
    accessibility: {
      menu: "Accesibilidad",
      settings: "Configuración de Accesibilidad",
      visualAlerts: "Alertas visuales",
      voiceReading: "Lectura por voz",
      voiceReadingHelp: "Pasa el mouse sobre botones, enlaces y títulos para escuchar su contenido",
      highContrast: "Modo alto contraste",
      largeText: "Texto ampliado",
      showShortcuts: "Mostrar atajos de teclado",
    },
    
    // Menú de usuario
    userMenu: {
      notificaciones: "Notificaciones",
      cerrarSesion: "Cerrar Sesión",
      organizadores: "Organizadores",
      organizador: "Organizador",
      adminCannotRegister: "Los administradores no pueden registrarse en proyectos. Puede gestionar proyectos desde el panel de administración.",
      organizerCannotRegister: "Los organizadores pueden crear y gestionar proyectos, pero no pueden registrarse como voluntarios.",
      alreadyRegistered: "Ya estás registrado en este proyecto.",
      gestionProyectos: "Gestión de Proyectos",
      proyectosAsignados: "Estos son los proyectos asignados a ti como organizador.",
      adminVerTodo: "Admin: puedes gestionar todos los proyectos",
      sinProyectosAsignados: "No tienes proyectos asignados.",
      editarProyectoTitulo: "Editar Proyecto",
    },
    
    // Página de inicio
    home: {
      badge: "Iniciativa Ambiental 2025",
      titulo1: "Renovemos el",
      titulo2: "Verde de Manabí",
      descripcion1: "Únete a nuestra misión de reforestar",
      hectareas: "10,000 hectáreas",
      descripcion2: "en Manabí. Cada árbol plantado es un paso hacia un futuro más verde y sostenible.",
      arbolesPlantados: "Árboles Plantados",
      hectareasLabel: "Hectáreas",
      voluntarios: "Voluntarios",
      plantarArbol: "Plantar un Árbol",
      verProyecto: "Ver el Proyecto",
      verProyectos: "Ver Proyectos",
      verEstadisticas: "Ver Estadísticas",
      personas: "+892 personas",
      seUnieron: "ya se unieron esta semana",
      arbolesNativos: "Árboles Nativos",
      especies: "23 Especies",
      co2Capturado: "CO₂ Capturado",
      toneladas: "1,245 Tons",
      donar: "Donar",
    },

    // Sistema de donaciones
    donacion: {
      titulo: "Hacer una Donación",
      cerrar: "Cerrar",
      paso1Titulo: "Selecciona un método de pago o agrega uno nuevo",
      metodosGuardados: "Métodos de pago guardados",
      agregarNuevaTarjeta: "Agregar nueva tarjeta",
      eliminarTarjeta: "Eliminar Tarjeta",
      confirmarEliminarTarjeta: "¿Estás seguro de que deseas eliminar esta tarjeta?",
      tarjetaEliminada: "Tarjeta eliminada correctamente",
      numeroTarjeta: "Número de tarjeta",
      numeroTarjetaPlaceholder: "1234 5678 9012 3456",
      nombreTitular: "Nombre del titular",
      nombreTitularPlaceholder: "JUAN PÉREZ",
      expiracion: "Expiración (MM/AA)",
      expiracionPlaceholder: "12/25",
      cvv: "CVV",
      cvvPlaceholder: "123",
      guardarTarjeta: "Guardar Tarjeta",
      cancelar: "Cancelar",
      tipo: "Tipo",
      tarjetaGuardada: "¡Tarjeta guardada!",
      tarjetaGuardadaMensaje: "Tu método de pago ha sido guardado correctamente",
      completarCampos: "Por favor completa todos los campos",
      paso2Titulo: "¿Cuánto te gustaría donar?",
      metodoPago: "Método de pago:",
      atras: "Atrás",
      donarMonto: "Donar",
      procesando: "Procesando...",
      montoInvalido: "Por favor ingresa un monto válido",
      exitoTitulo: "¡Donación Exitosa!",
      exitoMensaje: "Gracias por tu donación de",
      exitoDescripcion: "Tu generosa contribución ayudará a plantar más árboles y restaurar el ecosistema de Manabí. ¡Juntos estamos haciendo la diferencia! 🌳",
      fecha: "Fecha",
      finalizar: "Finalizar",
      donacionExitosa: "¡Donación exitosa!",
      donacionExitosaMensaje: "Gracias por tu donación. ¡Estás ayudando a reforestar Manabí!",
    },
    
    // Página de proyectos
    proyectos: {
      titulo: "Proyectos de Reforestación",
      descripcion: "Descubre y únete a nuestras iniciativas de reforestación en toda la provincia de Manabí",
      totalDe: "Total de",
      proyectos: "Proyectos",
      arboles: "Árboles",
      plantados: "Plantados",
      voluntarios: "Voluntarios",
      mapaInteractivo: "Mapa Interactivo de Proyectos",
      hacClicMarcadores: "Haz clic en los marcadores para ver información detallada de cada proyecto",
      cargandoMapa: "Cargando mapa...",
      cargando: "Cargando...",
      nuevaPeticion: "Nueva Petición de Proyecto",
      buscando: "Buscando",
    },
    
    // Estadísticas
    estadisticas: {
      titulo: "Mis Estadísticas",
      descripcion: "Monitorea tu progreso y contribución al medio ambiente",
      tuImpacto: "TU IMPACTO",
      arboles: "árboles",
      faltan: "Faltan",
      paraMeta: "para tu meta semanal",
      metaCumplida: "¡Meta cumplida! 🎉",
      deTuMeta: "de tu meta",
      metaSemanal: "Meta Semanal",
      arbolesPorSemana: "árboles por semana",
      editar: "Editar",
      estableceMeta: "Establece tu meta semanal",
      placeholderMeta: "Ej: 200",
      guardar: "Guardar",
      cancelar: "Cancelar",
      proyectosRegistrados: "Proyectos Registrados",
      proyectosActivos: "Proyectos Activos",
      proyectosProximos: "Proyectos Próximos",
      progresoMeta: "Progreso de Meta",
      desgloseContribucion: "Desglose de Contribución",
      arbolesEstimados: "árboles estimados",
      empiezaAventura: "¡Empieza tu Aventura Verde!",
      registrateProyectos: "Regístrate en proyectos de reforestación para ver tus estadísticas",
      explorarProyectos: "Explorar Proyectos",
    },
    
    // Perfil
    perfil: {
      titulo: "Mi Perfil",
      descripcion: "Administra tu información y proyectos de reforestación",
      misProyectos: "Mis Proyectos",
      noHayProyectos: "No hay proyectos registrados",
      noRegistrado: "Aún no te has registrado en ningún evento de reforestación",
      fecha: "Fecha",
      arboles: "Árboles",
      voluntarios: "Voluntarios",
      ubicacion: "Ubicación",
      especies: "Especies",
      registradoEl: "Registrado el",
      cancelarRegistro: "Cancelar Registro",
      verEstadisticas: "Ver Estadísticas Completas",
    },

    // Mapa de Proyectos
    mapaProyectos: {
      filtrarEstado: "Filtrar por estado:",
      todos: "Todos",
      proximo: "Próximo",
      activo: "Activo",
      finalizado: "Finalizado",
      fecha: "Fecha:",
      arboles: "Árboles:",
      voluntarios: "Voluntarios:",
      especies: "Especies:",
    },
    
    // Modal de registro
    modal: {
      seleccionaProyecto: "Selecciona un Proyecto",
      registroProyecto: "Registro al Proyecto",
      registrarse: "Registrarse",
      nombreCompleto: "Nombre Completo",
      email: "Email",
      telefono: "Teléfono",
      edad: "Edad",
      experiencia: "Experiencia en Reforestación",
      ninguna: "Ninguna",
      principiante: "Principiante (1-2 eventos)",
      intermedio: "Intermedio (3-5 eventos)",
      avanzado: "Avanzado (más de 5 eventos)",
      comentarios: "Comentarios o Preguntas",
      volver: "Volver",
      confirmarRegistro: "Confirmar Registro",
      registrando: "Registrando...",
      registroExitoso: "¡Registro Exitoso!",
      mensajeExito: "Te has registrado exitosamente al proyecto. Revisa tu perfil para más detalles.",
      cancelarRegistroTitulo: "¿Cancelar Registro?",
      cancelarRegistroMsg: "¿Estás seguro de que quieres cancelar tu registro al proyecto",
      noMantener: "No, Mantener",
      siCancelar: "Sí, Cancelar",
    },
    
    // Estados de proyectos
    estados: {
      activo: "Activo",
      proximo: "Próximo",
      completado: "Completado",
    },
    
    // Meses
    meses: {
      enero: "Enero",
      febrero: "Febrero",
      marzo: "Marzo",
      abril: "Abril",
      mayo: "Mayo",
      junio: "Junio",
      julio: "Julio",
      agosto: "Agosto",
      septiembre: "Septiembre",
      octubre: "Octubre",
      noviembre: "Noviembre",
      diciembre: "Diciembre",
    },
    
    // Login
    login: {
      titulo: "Bienvenido de Nuevo",
      subtitulo: "Ingresa a tu cuenta para continuar tu misión verde",
      email: "Correo Electrónico",
      contrasena: "Contraseña",
      recordarme: "Recordarme",
      olvidasteContrasena: "¿Olvidaste tu contraseña?",
      iniciarSesion: "Iniciar Sesión",
      iniciandoSesion: "Iniciando Sesión...",
      noTienesCuenta: "¿No tienes una cuenta?",
      registrate: "Regístrate aquí",
      emailRequerido: "El correo electrónico es requerido",
      contrasenaRequerida: "La contraseña es requerida",
      credencialesInvalidas: "Credenciales inválidas",
    },
    
    // Registro
    register: {
      titulo: "Únete a la Comunidad",
      subtitulo: "Crea tu cuenta y comienza a plantar árboles",
      nombreCompleto: "Nombre Completo",
      email: "Correo Electrónico",
      contrasena: "Contraseña",
      confirmarContrasena: "Confirmar Contraseña",
      telefono: "Teléfono (opcional)",
      ciudad: "Ciudad",
      aceptoTerminos: "Acepto los términos y condiciones",
      crearCuenta: "Crear Cuenta",
      creando: "Creando cuenta...",
      yaTienesCuenta: "¿Ya tienes una cuenta?",
      iniciarSesion: "Inicia sesión",
      nombreRequerido: "El nombre completo es requerido",
      emailRequerido: "El correo electrónico es requerido",
      contrasenaRequerida: "La contraseña es requerida",
      contrasenasNoCoinciden: "Las contraseñas no coinciden",
      ciudadRequerida: "La ciudad es requerida",
      aceptarTerminos: "Debes aceptar los términos y condiciones",
      registroExitoso: "¡Cuenta creada exitosamente!",
      emailYaRegistrado: "Este correo ya está registrado",
    },
    
    // Recuperar contraseña
    recuperar: {
      titulo: "Recuperar Contraseña",
      subtitulo: "Ingresa tu correo electrónico y te enviaremos instrucciones",
      email: "Correo Electrónico",
      enviarInstrucciones: "Enviar Instrucciones",
      enviando: "Enviando...",
      volverLogin: "Volver al inicio de sesión",
      exitoTitulo: "¡Revisa tu Correo!",
      exitoMensaje: "Hemos enviado instrucciones para recuperar tu contraseña. Por favor revisa tu bandeja de entrada.",
      emailRequerido: "El correo electrónico es requerido",
    },

    // Mis Proyectos (Perfil)
    misProyectos: {
      titulo: "Mis Proyectos",
      noProyectos: "No hay proyectos registrados",
      noProyectosDesc: "Aún no te has registrado en ningún evento de reforestación",
      explorarProyectos: "Explorar Proyectos",
      registradoEl: "Registrado el",
      cancelarRegistro: "Cancelar Registro",
      registrarAsistencia: "Registrar Asistencia",
      actualizar: "Actualizar",
      asistenciaRegistrada: "Asistencia Registrada",
      hasPlantado: "Has plantado",
      arboles: "árboles",
      fecha: "Fecha",
      voluntarios: "Voluntarios",
      ubicacion: "Ubicación",
      especies: "Especies",
      proyectoFinalizado: "Este proyecto ha finalizado. No se pueden realizar cambios.",
      
      // Modal de cancelación
      cancelarTitulo: "¿Cancelar Registro?",
      cancelarMensaje: "¿Estás seguro de que quieres cancelar tu registro al proyecto",
      noMantener: "No, Mantener",
      siCancelar: "Sí, Cancelar",
      
      // Modal de asistencia
      registrarAsistenciaTitulo: "Registrar Asistencia",
      ingresaCantidad: "Ingresa la cantidad de árboles que plantaste en este proyecto",
      arbolesPlantados: "Árboles Plantados",
      placeholderArboles: "Ej: 50",
      limiteProyecto: "Límite del proyecto",
      soloTuyos: "💡 Ingresa solo los árboles que tú plantaste personalmente",
      tuContribucion: "¡Tu contribución es valiosa!",
      ayudaraRastrear: "Esta información ayudará a rastrear el impacto real del proyecto",
      cancelar: "Cancelar",
      confirmar: "Confirmar",
      cantidadInvalida: "Por favor, ingresa una cantidad válida de árboles plantados",
      excedeLimite: "La cantidad no puede superar el límite del proyecto ({max} árboles)",
      asistenciaExito: "¡Asistencia registrada exitosamente! 🌳",
      errorRegistrar: "Error al registrar la asistencia",
    },

    // Widget de Impacto
    widgetImpacto: {
      tuImpacto: "TU IMPACTO",
      arboles: "árboles",
      plantados: "plantados",
      faltan: "Faltan",
      arbolesParaMeta: "árboles para tu meta semanal.",
      paraMeta: "para tu meta semanal",
      metaCumplida: "¡Meta cumplida!",
      metaSemanal: "Meta Semanal",
      progreso: "Progreso",
      verEstadisticas: "Ver Estadísticas Completas",
    },

    // Widget de Admin
    widgetAdmin: {
      panel: "PANEL ADMIN",
      proyectos: "proyectos",
      activos: "activos",
      voluntarios: "voluntarios",
    },

    // Panel de Administración
    admin: {
      titulo: "Panel de Administración",
      subtitulo: "Gestiona los proyectos de reforestación en Manabí",
      nuevoProyecto: "Nuevo Proyecto",
      noHayProyectos: "No hay proyectos",
      noHayProyectosDesc: "Comienza agregando tu primer proyecto de reforestación",
      agregarProyecto: "Agregar Proyecto",
      noProjects: "No Hay Proyectos Aún",
      noProjectsDesc: "Crea tu primer proyecto para comenzar",
      saveSuccess: "Proyecto guardado correctamente",
      deleteSuccess: "Proyecto eliminado correctamente",
      saveError: "Error al guardar el proyecto",
      deleteProject: "Eliminar Proyecto",
      confirmDelete: "¿Estás seguro de que quieres eliminar este proyecto?",
      cancel: "Cancelar",
      location: "Ubicación",
      trees: "Árboles",
      volunteers: "Voluntarios",
      species: "Especies",
      date: "Fecha",
      description: "Descripción",
      upcomingStatus: "Próximo",
      inProgressStatus: "En Progreso",
      completedStatus: "Completado",
      projectStatus: "Estado del proyecto",
      selectLocation: "Seleccionar ubicación",
      organizadores: "Organizadores",
      noOrganizersAvailable: "No hay organizadores disponibles. Agrega usuarios con rol organizador.",
      
      // Formulario
      editarProyecto: "Editar Proyecto",
      nombreProyecto: "Nombre del Proyecto",
      nombreProyectoPlaceholder: "Ej: Reforestación Parque Nacional Machalilla",
      ubicacion: "Ubicación (Ciudad/Cantón de Manabí)",
      seleccionaUbicacion: "Selecciona una ubicación",
      otraUbicacion: "Otra ubicación (personalizada)",
      escribeUbicacion: "Escribe la ubicación",
      coordenadas: "Coordenadas",
      coordenadasAyuda: "Las coordenadas se completan automáticamente al seleccionar una ubicación",
      coordenadasPersonalizadas: "Si necesitas coordenadas personalizadas, puedes usar",
      googleMaps: "Google Maps",
      googleMapsInfo: "(clic derecho → \"¿Qué hay aquí?\")",
      latitud: "Latitud",
      longitud: "Longitud",
      numeroArboles: "Número de Árboles",
      voluntariosNecesarios: "Voluntarios Necesarios",
      especies: "Especies (separadas por comas)",
      especiesPlaceholder: "Guayacán, Ceibo, Fernán Sánchez",
      fechaEvento: "Fecha del Evento",
      estado: "Estado",
      proximo: "Próximo",
      activo: "Activo",
      completado: "Completado",
      descripcion: "Descripción",
      descripcionPlaceholder: "Describe el proyecto de reforestación...",
      guardarCambios: "Guardar Cambios",
      crearProyecto: "Crear Proyecto",
      cancelar: "Cancelar",
      confirmarEliminar: "¿Estás seguro de eliminar este proyecto?",
      
      // Estadísticas
      verEstadisticas: "Ver Estadísticas",
      estadisticasProyecto: "Estadísticas del Proyecto",
      estadoProyecto: "Estado del Proyecto",
      fecha: "Fecha",
      ubicacionLabel: "Ubicación",
      progresoPlantacion: "Progreso de Plantación",
      arbolesPlantadosDe: "de",
      arbolesPlantados: "árboles plantados",
      meta: "Meta",
      plantados: "Plantados",
      restantes: "Restantes",
      participacionVoluntarios: "Participación de Voluntarios",
      voluntariosDe: "de",
      esperados: "Esperados",
      participantes: "Participantes",
      usuariosRegistrados: "Usuarios Registrados que Asistieron",
      noHayAsistencias: "Aún no hay usuarios que hayan registrado su asistencia",
      podranRegistrar: "Los usuarios podrán registrar su asistencia desde su perfil",
      arbolesPlantadosLabel: "Árboles plantados",
      informacionProyecto: "Información del Proyecto",
      especiesLabel: "Especies",
      descripcionLabel: "Descripción",
      sinDescripcion: "Sin descripción",
      voluntariosEsperados: "voluntarios",
      arbolesLabel: "Árboles",
      voluntariosLabel: "Voluntarios",
      especiesLabelCard: "Especies",
      fechaLabel: "Fecha",
      coordenadas: "Coordenadas",
      organizadores: "Organizadores",
      organizador: "Organizador",
      adminCannotRegister: "Los administradores no pueden registrarse en proyectos. Puedes gestionar los proyectos desde el panel de administración.",
      organizerCannotRegister: "Los organizadores pueden crear y gestionar proyectos, pero no registrarse como voluntarios.",
      alreadyRegistered: "Ya estás registrado en este proyecto.",
      gestionProyectos: "Gestión de Proyectos",
      proyectosAsignados: "Estos son los proyectos que te han sido asignados como organizador.",
      adminVerTodo: "Admin: puedes gestionar todos los proyectos",
      sinProyectosAsignados: "No tienes proyectos asignados.",
      editarProyectoTitulo: "Editar Proyecto",
    },
    
    // Panel de Control Admin
    adminDashboard: {
      titulo: "Panel de Control",
      subtitulo: "Vista general del sistema de reforestación",
      totalProyectos: "Total Proyectos",
      activos: "Activos",
      proximos: "Próximos",
      voluntariosActivos: "Voluntarios Activos",
      registrosTotales: "registros totales",
      asistenciasRegistradas: "Asistencias Registradas",
      participacionesConfirmadas: "Participaciones confirmadas",
      arbolesPlantados: "Árboles Plantados",
      impactoReal: "Impacto real confirmado",
      distribucionProyectos: "Distribución de Proyectos por Estado",
      proyectosActivos: "Proyectos Activos",
      proyectosProximos: "Proyectos Próximos",
      proyectosCompletados: "Proyectos Completados",
      actividadReciente: "Actividad Reciente",
      seRegistroEn: "Se registró en:",
      noHayActividad: "No hay actividad reciente",
      accesoRapido: "Acceso Rápido",
      gestionarProyectos: "Gestionar Proyectos",
      crearEditar: "Crear y editar",
      verVoluntarios: "Ver Voluntarios",
      listaCompleta: "Lista completa",
      asistencias: "Asistencias",
      gestionarRegistros: "Gestionar registros",
    },
    
    // Gestión de Voluntarios
    gestionVoluntarios: {
      titulo: "Gestión de Voluntarios",
      subtitulo: "Administra los voluntarios de cada proyecto",
      proyectos: "Proyectos",
      noProyectos: "No hay proyectos disponibles",
      voluntariosEn: "Voluntarios en",
      registrados: "registrados",
      buscar: "Buscar por nombre, email o teléfono...",
      edad: "Edad",
      anios: "años",
      experiencia: "Experiencia",
      disponibilidad: "Disponibilidad",
      transporte: "Transporte",
      verDetalle: "Ver detalle completo",
      noResultados: "No se encontraron resultados",
      noVoluntarios: "No hay voluntarios registrados en este proyecto",
      seleccionaProyecto: "Selecciona un proyecto",
      seleccionaProyectoDesc: "Elige un proyecto de la lista para ver sus voluntarios",
      detalleCompleto: "Detalle completo del voluntario",
      informacionContacto: "Información de Contacto",
      email: "Email",
      telefono: "Teléfono",
      proyecto: "Proyecto",
      nombreProyecto: "Nombre del proyecto",
      fechaRegistro: "Fecha de registro",
      perfilVoluntario: "Perfil del Voluntario",
      comentarios: "Comentarios adicionales",
      asistio: "Asistió",
      marcar: "Marcar",
      marcarAsistencia: "Marcar asistencia",
      quitarAsistencia: "Quitar asistencia",
      remover: "Remover voluntario",
      confirmRemove: "¿Estás seguro de que deseas eliminar este voluntario del proyecto?",
    },
    
    // Footer
    footer: {
      titulo: "Reforestación Manabí",
      descripcion: "Comprometidos con la restauración del ecosistema de Manabí a través de la reforestación sostenible y la participación comunitaria.",
      enlacesRapidos: "Enlaces Rápidos",
      contacto: "Contacto",
      ubicacion: "Manabí, Ecuador",
      siguenos: "Síguenos",
      redesSociales: "Únete a nuestra comunidad en redes sociales",
      derechosReservados: "Reforestación Manabí. Todos los derechos reservados.",
      hechoConAmor: "Hecho con",
      porVoluntarios: "por voluntarios",
      soporte: "Soporte",
      politica: "Política de Privacidad",
      terminos: "Términos de Uso",
    },
  },
  
  en: {
    // Common texts
    common: {
      cancel: "Cancel",
      accept: "Accept",
      edit: "Edit",
      delete: "Delete",
      save: "Save",
      help: "Help",
      create: "Create",
      saving: "Saving...",
      loading: "Loading...",
      newProject: "New Project",
      requests: "Requests",
      pending: "Pending",
      active: "Active",
      completed: "Completed",
      admin: "Admin",
      control: "Control",
      projectRequests: "Project Requests",
      noPendingRequests: "No pending requests",
      requestProject: "Request Project",
      search: "Search projects, locations...",
    },

    // Admin section translations
    admin: {
      titulo: "Administration Panel",
      subtitulo: "Manage reforestation projects in Manabí",
      projectRequests: "Project Requests",
      noPendingRequests: "No pending requests",
      viewRequests: "View Requests",
      requests: "Requests",
      editButton: "Edit",
      deleteButton: "Delete",
      confirmDelete: "Are you sure you want to delete this project?",
      editProject: "Edit Project",
      newProject: "New Project",
      requestProject: "Request Project",
      status: "Status",
      active: "Active",
      statsTitle: "Project Overview",
      totalProjects: "Total Projects",
      totalVolunteers: "Total Volunteers",
      noProjects: "No Projects Yet",
      noProjectsDesc: "Create your first project to get started",
      location: "Location",
      trees: "Trees",
      volunteers: "Volunteers",
      species: "Species",
      date: "Date",
      description: "Description",
      organizationInfo: "Organization Information",
      coordinates: "Coordinates",
      upcomingStatus: "Upcoming",
      inProgressStatus: "In Progress",
      completedStatus: "Completed",
      saveChanges: "Save Changes",
      projectName: "Project Name",
      projectNamePlaceholder: "Enter project name",
    },

    // Profile section
    profile: {
      editProfile: "Edit Profile",
      fullName: "Full Name",
      fullNamePlaceholder: "Your full name",
      email: "Email",
      emailPlaceholder: "example@email.com",
      role: "Role",
      organization: "Organization Information",
      orgName: "Organization Name",
      orgNamePlaceholder: "Organization name",
      website: "Website",
      websitePlaceholder: "https://...",
      changePassword: "Change Password (optional)",
      currentPassword: "Current Password",
      currentPasswordPlaceholder: "Required to change password",
      newPassword: "New Password",
      newPasswordPlaceholder: "Minimum 6 characters",
      nameRequired: "✕ Name required",
      invalidEmail: "✕ Invalid email",
      saveChanges: "Save Changes",
      cancel: "Cancel",
      validateFields: "Please correct the marked fields",
      enterCurrentPassword: "Enter your current password to change it",
      updateSuccess: "Profile updated successfully!",
      updatePasswordSuccess: "Profile and password updated successfully!",
      updateError: "Error updating profile",
      minChars: "✕ Minimum 6 characters",
    },

    // Admin section
    admin: {
      titulo: "Project Management",
      subtitulo: "Manage reforestation projects across Manabí",
      nuevoProyecto: "New Project",
      noHayProyectos: "No Projects Yet",
      noHayProyectosDesc: "Add your first project to get started",
      addProject: "Add Project",
      editProject: "Edit Project",
      deleteProject: "Delete Project",
      projectName: "Project Name",
      location: "Location",
      trees: "Trees",
      volunteers: "Volunteers",
      species: "Species",
      date: "Date",
      status: "Status",
      description: "Description",
      upcoming: "Upcoming",
      inProgress: "In Progress",
      completed: "Completed",
      save: "Save",
      cancel: "Cancel",
      confirmDelete: "Are you sure you want to delete this project?",
      noOrganizersAvailable: "No organizers available. Add users with organizer role.",
      deleteSuccess: "Project deleted successfully",
      saveSuccess: "Project saved successfully",
      selectLocation: "Select Location",
      otherLocation: "Other Location",
      writeLocation: "Enter location name",
      coordinates: "Coordinates",
      coordinatesHelp: "Click on the map to select coordinates or enter them manually",
      customCoordinates: "For custom coordinates, you can use",
      requestProject: "Request Project",
      projectDescription: "Description of the project",
      projectStatus: "Project Status",
      activeProjects: "Active Projects",
      upcomingStatus: "Upcoming",
      inProgressStatus: "In Progress",
      completedStatus: "Completed",
      organizers: "Organizers",
      organizersHelp: "Assign organizers to manage this project",
      saveProject: "Save Project",
      editProject: "Edit Project",
      deleteProject: "Delete Project",
      confirmDelete: "Are you sure you want to delete this project?",
      deleteSuccess: "Project deleted successfully",
      saveSuccess: "Project saved successfully",
      saveError: "Error saving project",
      peticiones: "Requests",
    },

    // Sidebar
    sidebar: {
      inicio: "Home",
      proyectos: "Projects",
      estadisticas: "Statistics",
      acceso: "Sign In",
      registro: "Sign Up",
      tuImpacto: "Your impact",
      arboles: "trees",
      faltan: "You need",
      arbolesParaMeta: "more trees to reach your weekly goal",
      modoOscuro: "Dark mode",
      modoClaro: "Light mode",
      espanol: "Español",
      ingles: "English",
      acceder: "Sign In",
      admin: "Administration",
      organizer: "Organizer",
      perfil: "Profile",
      control: "Control",
      voluntarios: "Volunteers",
    },

    // Accessibility menu
    accessibility: {
      menu: "Accessibility",
      settings: "Accessibility Settings",
      visualAlerts: "Visual alerts",
      voiceReading: "Voice reading",
      voiceReadingHelp: "Hover over buttons, links and titles to hear their content",
      highContrast: "High contrast mode",
      largeText: "Large text",
      showShortcuts: "Show keyboard shortcuts",
    },
    
    // User menu
    userMenu: {
      notificaciones: "Notifications",
      cerrarSesion: "Sign Out",
    },
    
    // Home page
    home: {
      badge: "Environmental Initiative 2025",
      titulo1: "Let's Renew",
      titulo2: "Manabí's Green",
      descripcion1: "Join our mission to reforest",
      hectareas: "10,000 hectares",
      descripcion2: "in Manabí. Every tree planted is a step towards a greener and more sustainable future.",
      arbolesPlantados: "Trees Planted",
      hectareasLabel: "Hectares",
      voluntarios: "Volunteers",
      plantarArbol: "Plant a Tree",
      verProyecto: "Watch Project",
      verProyectos: "View Projects",
      verEstadisticas: "View Statistics",
      personas: "+892 people",
      seUnieron: "joined this week",
      arbolesNativos: "Native Trees",
      especies: "23 Species",
      co2Capturado: "CO₂ Captured",
      toneladas: "1,245 Tons",
      donar: "Donate",
    },

    // Donation system
    donacion: {
      titulo: "Make a Donation",
      cerrar: "Close",
      paso1Titulo: "Select a payment method or add a new one",
      metodosGuardados: "Saved payment methods",
      agregarNuevaTarjeta: "Add new card",
      eliminarTarjeta: "Delete Card",
      confirmarEliminarTarjeta: "Are you sure you want to delete this card?",
      tarjetaEliminada: "Card deleted successfully",
      numeroTarjeta: "Card number",
      numeroTarjetaPlaceholder: "1234 5678 9012 3456",
      nombreTitular: "Cardholder name",
      nombreTitularPlaceholder: "JOHN DOE",
      expiracion: "Expiration (MM/YY)",
      expiracionPlaceholder: "12/25",
      cvv: "CVV",
      cvvPlaceholder: "123",
      guardarTarjeta: "Save Card",
      cancelar: "Cancel",
      tipo: "Type",
      tarjetaGuardada: "Card saved!",
      tarjetaGuardadaMensaje: "Your payment method has been saved successfully",
      completarCampos: "Please complete all fields",
      paso2Titulo: "How much would you like to donate?",
      metodoPago: "Payment method:",
      atras: "Back",
      donarMonto: "Donate",
      procesando: "Processing...",
      montoInvalido: "Please enter a valid amount",
      exitoTitulo: "Donation Successful!",
      exitoMensaje: "Thank you for your donation of",
      exitoDescripcion: "Your generous contribution will help plant more trees and restore the Manabí ecosystem. Together we are making a difference! 🌳",
      fecha: "Date",
      finalizar: "Finish",
      donacionExitosa: "Donation successful!",
      donacionExitosaMensaje: "Thank you for your donation. You're helping to reforest Manabí!",
    },
    
    // Projects page
    proyectos: {
      titulo: "Reforestation Projects",
      descripcion: "Discover and join our reforestation initiatives throughout the province of Manabí",
      totalDe: "Total",
      proyectos: "Projects",
      arboles: "Trees",
      plantados: "Planted",
      voluntarios: "Volunteers",
      mapaInteractivo: "Interactive Project Map",
      hacClicMarcadores: "Click on markers to see detailed information about each project",
      cargandoMapa: "Loading map...",
      cargando: "Loading...",
      nuevaPeticion: "New Project Request",
      buscando: "Searching",
    },
    
    // Statistics
    estadisticas: {
      titulo: "My Statistics",
      descripcion: "Monitor your progress and environmental contribution",
      tuImpacto: "YOUR IMPACT",
      arboles: "trees",
      faltan: "You need",
      paraMeta: "for your weekly goal",
      metaCumplida: "Goal achieved! 🎉",
      deTuMeta: "of your goal",
      metaSemanal: "Weekly Goal",
      arbolesPorSemana: "trees per week",
      editar: "Edit",
      estableceMeta: "Set your weekly goal",
      placeholderMeta: "E.g: 200",
      guardar: "Save",
      cancelar: "Cancel",
      proyectosRegistrados: "Registered Projects",
      proyectosActivos: "Active Projects",
      proyectosProximos: "Upcoming Projects",
      progresoMeta: "Goal Progress",
      desgloseContribucion: "Contribution Breakdown",
      arbolesEstimados: "estimated trees",
      empiezaAventura: "Start Your Green Adventure!",
      registrateProyectos: "Register for reforestation projects to see your statistics",
      explorarProyectos: "Explore Projects",
    },
    
    // Profile
    perfil: {
      titulo: "My Profile",
      descripcion: "Manage your information and reforestation projects",
      misProyectos: "My Projects",
      noHayProyectos: "No registered projects",
      noRegistrado: "You haven't registered for any reforestation events yet",
      fecha: "Date",
      arboles: "Trees",
      voluntarios: "Volunteers",
      ubicacion: "Location",
      especies: "Species",
      registradoEl: "Registered on",
      cancelarRegistro: "Cancel Registration",
      verEstadisticas: "View Full Statistics",
    },

    // Project Map
    mapaProyectos: {
      filtrarEstado: "Filter by status:",
      todos: "All",
      proximo: "Upcoming",
      activo: "Active",
      finalizado: "Completed",
      fecha: "Date:",
      arboles: "Trees:",
      voluntarios: "Volunteers:",
      especies: "Species:",
    },
    
    // Registration modal
    modal: {
      seleccionaProyecto: "Select a Project",
      registroProyecto: "Project Registration",
      registrarse: "Register",
      nombreCompleto: "Full Name",
      email: "Email",
      telefono: "Phone",
      edad: "Age",
      experiencia: "Reforestation Experience",
      ninguna: "None",
      principiante: "Beginner (1-2 events)",
      intermedio: "Intermediate (3-5 events)",
      avanzado: "Advanced (more than 5 events)",
      comentarios: "Comments or Questions",
      volver: "Back",
      confirmarRegistro: "Confirm Registration",
      registrando: "Registering...",
      registroExitoso: "Registration Successful!",
      mensajeExito: "You have successfully registered for the project. Check your profile for more details.",
      cancelarRegistroTitulo: "Cancel Registration?",
      cancelarRegistroMsg: "Are you sure you want to cancel your registration for the project",
      noMantener: "No, Keep It",
      siCancelar: "Yes, Cancel",
    },
    
    // Project statuses
    estados: {
      activo: "Active",
      proximo: "Upcoming",
      completado: "Completed",
    },
    
    // Months
    meses: {
      enero: "January",
      febrero: "February",
      marzo: "March",
      abril: "April",
      mayo: "May",
      junio: "June",
      julio: "July",
      agosto: "August",
      septiembre: "September",
      octubre: "October",
      noviembre: "November",
      diciembre: "December",
    },
    
    // Login
    login: {
      titulo: "Welcome Back",
      subtitulo: "Sign in to your account to continue your green mission",
      email: "Email Address",
      contrasena: "Password",
      recordarme: "Remember me",
      olvidarContrasena: "Forgot your password?",
      iniciarSesion: "Sign In",
      iniciando: "Signing in...",
      noTienesCuenta: "Don't have an account?",
      registrate: "Sign up here",
      emailRequerido: "Email is required",
      contrasenaRequerida: "Password is required",
      credencialesInvalidas: "Invalid credentials",
    },
    
    // Register
    register: {
      titulo: "Join the Community",
      subtitulo: "Create your account and start planting trees",
      nombreCompleto: "Full Name",
      email: "Email Address",
      contrasena: "Password",
      confirmarContrasena: "Confirm Password",
      telefono: "Phone (optional)",
      ciudad: "City",
      aceptoTerminos: "I accept the terms and conditions",
      crearCuenta: "Create Account",
      creando: "Creating account...",
      yaTienesCuenta: "Already have an account?",
      iniciarSesion: "Sign in",
      nombreRequerido: "Full name is required",
      emailRequerido: "Email is required",
      contrasenaRequerida: "Password is required",
      contrasenasNoCoinciden: "Passwords don't match",
      ciudadRequerida: "City is required",
      aceptarTerminos: "You must accept the terms and conditions",
      registroExitoso: "Account created successfully!",
      emailYaRegistrado: "This email is already registered",
    },
    
    // Password recovery
    recuperar: {
      titulo: "Recover Password",
      subtitulo: "Enter your email and we'll send you instructions",
      email: "Email Address",
      enviarInstrucciones: "Send Instructions",
      enviando: "Sending...",
      volverLogin: "Back to sign in",
      exitoTitulo: "Check Your Email!",
      exitoMensaje: "We've sent password recovery instructions. Please check your inbox.",
      emailRequerido: "Email is required",
    },

    // My Projects (Profile)
    misProyectos: {
      titulo: "My Projects",
      noProyectos: "No registered projects",
      noProyectosDesc: "You haven't registered for any reforestation events yet",
      explorarProyectos: "Explore Projects",
      registradoEl: "Registered on",
      cancelarRegistro: "Cancel Registration",
      registrarAsistencia: "Register Attendance",
      actualizar: "Update",
      asistenciaRegistrada: "Attendance Registered",
      hasPlantado: "You have planted",
      arboles: "trees",
      fecha: "Date",
      voluntarios: "Volunteers",
      ubicacion: "Location",
      especies: "Species",
      proyectoFinalizado: "This project has ended. No changes can be made.",
      
      // Cancellation modal
      cancelarTitulo: "Cancel Registration?",
      cancelarMensaje: "Are you sure you want to cancel your registration for the project",
      noMantener: "No, Keep It",
      siCancelar: "Yes, Cancel",
      
      // Attendance modal
      registrarAsistenciaTitulo: "Register Attendance",
      ingresaCantidad: "Enter the number of trees you planted in this project",
      arbolesPlantados: "Trees Planted",
      placeholderArboles: "e.g., 50",
      limiteProyecto: "Project limit",
      soloTuyos: "💡 Enter only the trees you personally planted",
      tuContribucion: "Your contribution is valuable!",
      ayudaraRastrear: "This information will help track the project's real impact",
      cancelar: "Cancel",
      confirmar: "Confirm",
      cantidadInvalida: "Please enter a valid number of planted trees",
      excedeLimite: "The amount cannot exceed the project limit ({max} trees)",
      asistenciaExito: "Attendance registered successfully! 🌳",
      errorRegistrar: "Error registering attendance",
    },

    // Impact Widget
    widgetImpacto: {
      tuImpacto: "YOUR IMPACT",
      arboles: "trees",
      plantados: "planted",
      faltan: "You need",
      arbolesParaMeta: "more trees to reach your weekly goal.",
      paraMeta: "for your weekly goal",
      metaCumplida: "Goal achieved!",
      metaSemanal: "Weekly Goal",
      progreso: "Progress",
      verEstadisticas: "View Full Statistics",
    },

    // Admin Widget
    widgetAdmin: {
      panel: "ADMIN PANEL",
      proyectos: "projects",
      activos: "active",
      voluntarios: "volunteers",
    },

    // Admin Panel
      admin: {
      titulo: "Administration Panel",
      subtitulo: "Manage reforestation projects in Manabí",
      nuevoProyecto: "New Project",
      noHayProyectos: "No projects",
      noHayProyectosDesc: "Start by adding your first reforestation project",
      agregarProyecto: "Add Project",
      noProjects: "No Projects Yet",
      noProjectsDesc: "Create your first project to get started",
      saveSuccess: "Project saved successfully",
      deleteSuccess: "Project deleted successfully",
      saveError: "Error saving project",
      deleteProject: "Delete Project",
      confirmDelete: "Are you sure you want to delete this project?",
      cancel: "Cancel",
      location: "Location",
      trees: "Trees",
      volunteers: "Volunteers",
      species: "Species",
      date: "Date",
      description: "Description",
      upcomingStatus: "Upcoming",
      inProgressStatus: "In Progress",
      completedStatus: "Completed",
      projectStatus: "Project Status",
      selectLocation: "Select location",
      organizadores: "Organizers",
      noOrganizersAvailable: "No organizers available. Add users with organizer role.",
      
      // Form
      editarProyecto: "Edit Project",
      nombreProyecto: "Project Name",
      nombreProyectoPlaceholder: "e.g., Machalilla National Park Reforestation",
      ubicacion: "Location (City/Canton in Manabí)",
      seleccionaUbicacion: "Select a location",
      otraUbicacion: "Other location (custom)",
      escribeUbicacion: "Enter the location",
      coordenadas: "Coordinates",
      coordenadasAyuda: "Coordinates are automatically filled when you select a location",
      coordenadasPersonalizadas: "If you need custom coordinates, you can use",
      googleMaps: "Google Maps",
      googleMapsInfo: "(right-click → \"What's here?\")",
      latitud: "Latitude",
      longitud: "Longitude",
      numeroArboles: "Number of Trees",
      voluntariosNecesarios: "Volunteers Needed",
      especies: "Species (comma-separated)",
      especiesPlaceholder: "Guayacan, Ceibo, Fernan Sanchez",
      fechaEvento: "Event Date",
      estado: "Status",
      proximo: "Upcoming",
      activo: "Active",
      completado: "Completed",
      descripcion: "Description",
      descripcionPlaceholder: "Describe the reforestation project...",
      guardarCambios: "Save Changes",
      crearProyecto: "Create Project",
      cancelar: "Cancel",
      confirmarEliminar: "Are you sure you want to delete this project?",      // Statistics
      verEstadisticas: "View Statistics",
      estadisticasProyecto: "Project Statistics",
      estadoProyecto: "Project Status",
      fecha: "Date",
      ubicacionLabel: "Location",
      progresoPlantacion: "Planting Progress",
      arbolesPlantadosDe: "of",
      arbolesPlantados: "trees planted",
      meta: "Goal",
      plantados: "Planted",
      restantes: "Remaining",
      participacionVoluntarios: "Volunteer Participation",
      voluntariosDe: "of",
      esperados: "Expected",
      participantes: "Participants",
      usuariosRegistrados: "Registered Users Who Attended",
      noHayAsistencias: "No users have registered their attendance yet",
      podranRegistrar: "Users will be able to register their attendance from their profile",
      arbolesPlantadosLabel: "Trees planted",
      informacionProyecto: "Project Information",
      especiesLabel: "Species",
      descripcionLabel: "Description",
      sinDescripcion: "No description",
      voluntariosEsperados: "volunteers",
      arbolesLabel: "Trees",
      voluntariosLabel: "Volunteers",
      especiesLabelCard: "Species",
      fechaLabel: "Date",
      coordenadas: "Coordinates",
      organizadores: "Organizers",
      organizador: "Organizer",
      adminCannotRegister: "Administrators cannot register for projects. You can manage projects from the admin panel.",
      organizerCannotRegister: "Organizers can create and manage projects, but cannot register as volunteers.",
      alreadyRegistered: "You are already registered for this project.",
      gestionProyectos: "Project Management",
      proyectosAsignados: "These are the projects assigned to you as an organizer.",
      adminVerTodo: "Admin: you can manage all projects",
      sinProyectosAsignados: "You have no projects assigned.",
      editarProyectoTitulo: "Edit Project",
    },
    
    // Admin Control Panel
    adminDashboard: {
      titulo: "Control Panel",
      subtitulo: "Overview of the reforestation system",
      totalProyectos: "Total Projects",
      activos: "Active",
      proximos: "Upcoming",
      voluntariosActivos: "Active Volunteers",
      registrosTotales: "total registrations",
      asistenciasRegistradas: "Registered Attendances",
      participacionesConfirmadas: "Confirmed participations",
      arbolesPlantados: "Trees Planted",
      impactoReal: "Real confirmed impact",
      distribucionProyectos: "Projects Distribution by Status",
      proyectosActivos: "Active Projects",
      proyectosProximos: "Upcoming Projects",
      proyectosCompletados: "Completed Projects",
      actividadReciente: "Recent Activity",
      seRegistroEn: "Registered in:",
      noHayActividad: "No recent activity",
      accesoRapido: "Quick Access",
      gestionarProyectos: "Manage Projects",
      crearEditar: "Create and edit",
      verVoluntarios: "View Volunteers",
      listaCompleta: "Complete list",
      asistencias: "Attendances",
      gestionarRegistros: "Manage records",
    },
    
    // Volunteer Management
    gestionVoluntarios: {
      titulo: "Volunteer Management",
      subtitulo: "Manage volunteers for each project",
      proyectos: "Projects",
      noProyectos: "No projects available",
      voluntariosEn: "Volunteers in",
      registrados: "registered",
      buscar: "Search by name, email or phone...",
      edad: "Age",
      anios: "years old",
      experiencia: "Experience",
      disponibilidad: "Availability",
      transporte: "Transport",
      verDetalle: "View full details",
      noResultados: "No results found",
      noVoluntarios: "No volunteers registered for this project",
      seleccionaProyecto: "Select a project",
      seleccionaProyectoDesc: "Choose a project from the list to view its volunteers",
      detalleCompleto: "Full volunteer details",
      informacionContacto: "Contact Information",
      email: "Email",
      telefono: "Phone",
      proyecto: "Project",
      nombreProyecto: "Project name",
      fechaRegistro: "Registration date",
      perfilVoluntario: "Volunteer Profile",
      comentarios: "Additional comments",
      asistio: "Attended",
      marcar: "Mark",
      marcarAsistencia: "Mark attendance",
      quitarAsistencia: "Remove attendance",
      remover: "Remove volunteer",
      confirmRemove: "Are you sure you want to remove this volunteer from the project?",
    },
    
    // Footer
    footer: {
      titulo: "Reforestation Manabí",
      descripcion: "Committed to restoring the Manabí ecosystem through sustainable reforestation and community participation.",
      enlacesRapidos: "Quick Links",
      contacto: "Contact",
      ubicacion: "Manabí, Ecuador",
      siguenos: "Follow Us",
      redesSociales: "Join our social media community",
      derechosReservados: "Reforestation Manabí. All rights reserved.",
      hechoConAmor: "Made with",
      porVoluntarios: "by volunteers",
      soporte: "Support",
      politica: "Privacy Policy",
      terminos: "Terms of Use",
    },
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('es');

  useEffect(() => {
    // Cargar idioma guardado
    try {
      const savedLanguage = localStorage.getItem('language');
      if (savedLanguage && (savedLanguage === 'es' || savedLanguage === 'en')) {
        setLanguage(savedLanguage);
      }
    } catch (e) {
      console.error('Error loading language:', e);
    }

    // Escuchar cambios de idioma
    const handleLanguageChange = () => {
      try {
        const savedLanguage = localStorage.getItem('language');
        if (savedLanguage && (savedLanguage === 'es' || savedLanguage === 'en')) {
          setLanguage(savedLanguage);
        }
      } catch (e) {
        console.error('Error updating language:', e);
      }
    };

    window.addEventListener('languageChange', handleLanguageChange);
    return () => window.removeEventListener('languageChange', handleLanguageChange);
  }, []);

  const t = (key) => {
    const keys = key.split('.');
    let value = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
      if (value === undefined) {
        console.warn(`Translation missing for key: ${key}`);
        return key;
      }
    }
    
    return value;
  };

  const toggleLanguage = () => {
    const newLanguage = language === 'es' ? 'en' : 'es';
    setLanguage(newLanguage);
    try {
      localStorage.setItem('language', newLanguage);
      window.dispatchEvent(new Event('languageChange'));
    } catch (e) {
      console.error('Error saving language:', e);
    }
  };

  return (
    <LanguageContext.Provider value={{ language, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
